services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vroom-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      - ALLOWED_ORIGINS=http://localhost:5173
    # Mount local folder into the container's working directory
    volumes:
      - ./backend:/app
      - ./backend/images:/app/images
    # Override the Dockerfile CMD to inject the --reload flag for local development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy
    networks:
      - vroom-network

  frontend:
    build:
      context: ./frontend
      # Targets 'dev' stage containing the Vite development server
      target: dev 
    ports:
      - "5173:5173" # Maps to Vite's default dev server port
    # Mount the frontend folder and shield node_modules
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - vroom-network

volumes:
  postgres_data:

networks:
  vroom-network: